// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wzpgupzoyfagzoyygbro.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind6cGd1cHpveWZhZ3pveXlnYnJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNzkxNjgsImV4cCI6MjA2MDk1NTE2OH0.cUKeCVRI_dy--RjIJQtgC4dKjrNIouMJiJMR85M2neg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);